## TIL 0728



### 예외처리



오류를 회피하거나 처리하기 위해 사용한다.

try:



except:



else:



finally:

정도로 구성된다.



try문을 실행한다. 에러가 발생한다면 except문을 실행한다.

이 때, except ValueError: 식으로 특정한 오류만 지정할 수도 있다.

except 여러 개 쓸 수 있다.



else: 구문으로 에러가 발생하지 않았을 경우의 행동을 정할 수 있다.

? 만약 except 특정에러 헀는데 다른 에러가 날 경우는 어떡하지?

그냥 에러로 진행되지 않는다.

특정 에러 잘 집어냈다면? pass등 가능




